### ISSUE TITLE
undefined method `each_pair' for [#<OpenStruct type="subscriptions" ...

### ISSUE THREAD

**Issue by ricvillagrana** [deanpcmad/lemonsqueezy#2]
It successfully retrieves the information but got this error when the gem tries to format the object in `lib/lemon_squeezy/object.rb:6`.

Trace:
```
[/Users/ricardovillagrana/.rbenv/versions/3.1.3/lib/ruby/3.1.0/ostruct.rb:147:in `update_to_values!'](http://localhost:7000/subscriptions#)
[/Users/ricardovillagrana/.rbenv/versions/3.1.3/lib/ruby/3.1.0/ostruct.rb:128:in `initialize'](http://localhost:7000/subscriptions#)
[lemonsqueezy (0.2.2) lib/lemon_squeezy/object.rb:6:in `initialize'](http://localhost:7000/subscriptions#)
[lemonsqueezy (0.2.2) lib/lemon_squeezy/objects/subscription.rb:8:in `initialize'](http://localhost:7000/subscriptions#)
[lemonsqueezy (0.2.2) lib/lemon_squeezy/resources/subscriptions.rb:11:in `new'](http://localhost:7000/subscriptions#)
[lemonsqueezy (0.2.2) lib/lemon_squeezy/resources/subscriptions.rb:11:in `get'](http://localhost:7000/subscriptions#)
```

Happy to share more info if needed.

**Comment by deanpcmad** [comment]
What method are you trying to use, as I'm not seeing this error when using `subscriptions.list` or `subscriptions.get id: 123`
